# .streamlit/secrets.toml

[connections.snowflake]
account = "HFTFTRX-WP80054"
user = "gjruppert"
password = "8kvt5jmwpB&5nLf8"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
